# .circleci/config.yml

# Specify the config version - version 2 is latest.
version: 2

# Define the jobs for the current project.
jobs:
  build-and-test:
    environment:
      # Public - Yay
      UPLOAD_IOS_SNAPSHOT_BUCKET_NAME: eigen-ci

      # Private - Keeps us in business! Yay
      #   AWS_ACCESS_KEY_ID: from_admin
      #   AWS_SECRET_ACCESS_KEY: from_admin
      #   DANGER_GITHUB_API_TOKEN: from_admin
      #   MATCH_PASSWORD : from_admin
      #   HOCKEY_API_TOKEN : from_admin
      #   FASTLANE_USERNAME : from_admin
      #   FASTLANE_PASSWORD : from_admin
      #   ArtsyAPIClientSecret: from_admin
      #   ArtsyAPIClientKey: from_admin
      #   ArtsyFacebookAppID: from_admin
      #   ArtsyTwitterKey: from_admin
      #   ArtsyTwitterSecret: from_admin
      #   ArtsyTwitterStagingKey: from_admin
      #   ArtsyTwitterStagingSecret: from_admin
      #   SegmentProductionWriteKey: from_admin
      #   SegmentDevWriteKey: from_admin
      #   AdjustProductionAppToken: from_admin
      #   ArtsyEchoProductionToken:  from_admin
      BUNDLE_PATH: vendor/bundle  # path to install gems and use for caching

    # Specify the Xcode version to use.
    macos:
      xcode: "9.3.0"

    # Define the steps required to build the project.
    steps:

      # Get the code from the VCS provider.
      - checkout

      - restore_cache:
          keys:
          - v1-gems-{{ checksum "Gemfile.lock" }}
          # Fall back to using the latest cache if no exact match is found.
          - v1-gems-

      # Install gems.
      - run:
          name: Bundle install
          command: bundle check || bundle install
          environment:
            BUNDLE_JOBS: 4
            BUNDLE_RETRY: 3

      - save_cache:
          key: v1-gems-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - run:
          name: List sims
          command: xcversion simulators
 
      - run:
          name: List devices
          command: instruments -s devices

      - restore_cache:
          keys:
          - v2-pods-{{ checksum "Podfile.lock" }}
          # Fall back to using the latest cache if no exact match is found.
          - v2-pods-

      - run:
          name: Install CocoaPods
          command: bundle exec pod check || curl https://cocoapods-specs.circleci.com/fetch-cocoapods-repo-from-s3.sh | bash -s cf

      - run:
          name: Install Pods
          command: bundle exec pod check || bundle exec pod install

      - save_cache:
          key: v2-pods-{{ checksum "Podfile.lock" }}
          paths:
            - Pods

      - run:
          name: Pre-Build App
          command: make ci

      - run:
          name: Run tests
          command: make test

      - store_artifacts:
          path: xcode_build_raw.log
          prefix: build

      - store_artifacts:
          path: xcode_test_raw.log
          prefix: tests

      - store_test_results:
          path: test-results.xml
  
      - run:
          name: Danger
          command: bundle exec danger --danger_id=circle --dangerfile=Dangerfile.circle.rb --verbose
      
      - run:
          name: Deploy if beta
          command: make deploy_if_beta_branch


workflows:
  version: 2
  build-test:
    jobs:
      - build-and-test
